- boot/am335x_evm.sh
- boot/autoconfigure_usb0.sh
network-values for usb0 from /etc/network/interfaces, instead of
having them hardcoded into the script itself.
If udhcpd is installed, changing /etc/network/interfaces will cause
the scripts to reconfigure /etc/udhcpd.conf (provided that the udhcpd
interface is set to usb0).
If dnsmasq is installed (and udhcpd is not), changing
/etc/network/interfaces will cause the scripts to reconfigure
/etc/dnsmasq.d/usb0-dhcp.generated accordingly, only if no other
configuration file references usb0.  The usb0-dhcp.generated filename
can be appended with ~ (tilde) to disable further reconfiguration.
Signed-off-by: Per Dalgas Jakobsen <pdj@knaldgas.dk>
> The am335x_evm.sh script will, through autoconfigure_usb0.sh, read the

- boot/am335x_evm.sh
Prior to checking partition setup, check for image file and load this as USB mass storage gadget instead of boot partition.
The image file could be created or downloaded by starting a script. It should contain the drivers and a getting started guide.
> Boot: load g_multi with image file if that exists

- boot/autoconfigure_usb0.sh
Setting `port=0` disables dnsmasq' DNS, which in turn renders DNS non-functional, because so long as dnsmasq is running /etc/resolv.conf lists 127.0.0.1 (i.e., dnsmasq) as the DNS server. (mDNS will still work, though.) Adding `except-interface=wlan0` does not rescue this; according to the documentation, `except-interface`, `interface` and `listen-address` are three different alternatives to determine where dnsmasq listens, hence mixing them doesn't really make sense. Using `interface=` will implicitly include the loopback interface, but using `listen-address` will _not_. Without lo or localhost being listened to by dnsmasq, DNS will not work.
> Fixes dnsmasq configuration to work with wireless interfaces too

- boot/autoconfigure_usb0.sh
I'm tired of leases getting hung up between disconnects. This might be
due to MAC address changes, but a few extra DHCP requests seems like
a small price to pay to ensure users aren't waiting around for minutes
on end to get a valid IP address on their machine.
> autoconfigure_usb0: udhcpd 30 leases

- boot/am335x_evm.sh
- boot/autoconfigure_usb1.sh
This adds a CDC/EMC USB networking function to the multifunction
USB gadget device. This is needed to get USB networking working on
macOS with no 3rd party drivers. It also works better than RNDIS on
Linux. Also, we will be changing the USB class of the RNDIS driver,
so it will no longer be detected by Linux, so CDC will be the only
networking interface that shows up on Linux.
> Add CDC/ECM function to USB gadget

- boot/am335x_evm.sh
This adds a second USB gadget configuration that will be used by Linux.
Linux is smart enough to know that RNDIS is not nice, so if it sees RNDIS
as the first interface and it sees that there is a second USB configuration,
it will prefer the second configuration. This results in only the CDC ECM
interface being used on Linux (and older versions of macOS).
> Add a second USB gadget configuration for Linux

- boot/autoconfigure_usb0.sh
Moved the "post_up" and "nameserver" setting lines outside of the if statement so that it runs regardless whether the usb_gadget folder exists or not.
> Fix autosetting default gateway and nameservers

- boot/am335x_evm.sh
This adds an if block to check if the attributes added in kernel 4.14 are present and use them.
Changes were introduced in this kernel commit:
https://github.com/beagleboard/linux/commit/73517cf49bd449122b615d2b7a6bb835f02252e5
I haven't actually tested these changes, but they should allow you to drop https://github.com/beagleboard/linux/commit/e94487c59cec8ba32dc1eb83900297858fdc590b from the v4.14 bb.org kernel.
> Add support for new RNDIS configfs options in kernel 4.14

- boot/am335x_evm.sh
Reverts RobertCNelson/boot-scripts#64
I just realized that I did this for the wrong function, ecm instead of rndis.
> Revert "Add support for new RNDIS configfs options in kernel 4.14"

- boot/am335x_evm.sh
Add support for bb-boot config file,
and honor the USB_IMAGE_FILE_DISABLED variable.
refs #67 #63
> Add support for bb-boot config file

- boot/am335x_evm.sh
These values need to be hex (without 0x prefix), not decimal.
> Fix kernel 4.14 kernel RNDIS class

- tools/update_kernel.sh
This allows mounting and chrooting into a BBB image on a more robust ARMv7 system to prepare the image. In particular, without this tweak, the logic deciding what other packages should be installed along with the kernel doesn't work.
> add FORCEMACHINE to support updating the kernel in an offline image

- boot/autoconfigure_usb1.sh
User may have added an ifupdown configuration for 'usb1'.
In this case the user's assumption is that their ifupdown config
would be the one applied to the interface when brought up.
Maintain the default behavior as before: in absence of user directive
configure usb1 with the time-honored static IP.
Signed-off-by: Sirio Balmelli <sirio@b-ad.ch>
> Respect any existing ifup configuration when bringing 'usb1' online.

- boot/am335x_evm.sh
User may not want automatic creation/overwriting of dnsmasq SoftAp0 file,
allow disabling with a dotfile.
Signed-off-by: Sirio Balmelli <sirio@b-ad.ch>
> Allow user to disable /etc/dnsmasq.d/SoftAp0 creation using a dotfile.

- tools/grow_partition.sh
The two error messages for when the drive could not be detected outputted
```
Error: script halting, could detect drive...
```
instead of
```
Error: script halting, could not detect drive...
```
> Added missing 'not' in error messages when drive not detected

- boot/am335x_evm.sh
Since this usb network card has no MAC address inside the chip, we need to set up a random MAC address to fix the IP address
> add mac address for seeedstuido beaglebone green gateway

- boot/am335x_evm.sh
A typo in the script caused it to crash
> Removed a typo in am335x_evm.sh

- boot/am335x_evm.sh
There was no support for the Wireless Connectivity Cape for BeagleBone Black (AKA Gateway Cape).
Without this patch, after adding to /boot/uEnv.txt:
```
uboot_overlay_addr4=/lib/firmware/BB-GATEWAY-WL1837-00A0.dtbo
``` 
the board boots, but the USB network interfaces are not properly set.
> Add support to the Gateway Cape for BeagleBone Black

- boot/am335x_evm.sh
- boot/bbai.sh
- boot/bbai_usb_gadget.sh
- boot/beagle_x15.sh
The USB CDC Ethernet gadget is currently configured to use the ECM
protocol.  Unfortunately this protocol is no longer supported by
MacOS hosts.  However, the newer NCM protocol is supported.
The NCM protocol is also supported by Linux hosts.
This patch updates the USB CDC Ethernet gadget configuration scripts
to use the NCM protocol instead of the ECM protocol.
The patch has been tested on MacOS 10.15.4 using a pocketbeagle.
It is untested on other beagle hardware.
Signed-off-by: James Kelly <vk3jpk@gmail.com>
> boot: Update USB CDC Ethernet gadget to use NCM

- boot/am335x_evm.sh
- tools/eMMC/functions.sh
- tools/eMMC/init-eMMC-flasher-v2.sh
- tools/generate_extlinux.sh
- tools/grow_partition.sh
To avoid confused by something like "overlayroot=" or "nfsroot=".
Signed-off-by: Atsushi Nemoto <atsushi.nemoto@sord.co.jp>
> use "grep ^root=" instead of "grep root=" when parsing /proc/cmdline

- tools/eMMC/functions.sh
Setting the conf_rootfs_partition_size variable allows for better control over the size of the microSD card necessary to house the resulting image when running the beaglebone-black-make-microSD-flasher-from-eMMC.sh script. For example, you might be working with a 32GB microSD card image, but want to generate an image that would also fit on a 4GB microSD card, so you could do the following:
sudo conf_rootfs_partition_size=7462912 /opt/scripts/tools/eMMC/beaglebone-black-make-microSD-flasher-from-eMMC.sh
Which would specify the size as 7462912 sectors, which is the size of the eMMC rootfs partition (at least on the one I was testing on). After making the flasher you could then use dd to get the image off the microSD card for flashing onto other microSD cards:
sudo dd if=<path to microSD …
> added conf_rootfs_partition_size

- boot/generic-startup.sh
- tools/grow_partition.sh
I've made progress getting a process in place that can convert a Beaglebone image to an ostree-managed version of it. When the ostree-managed system is running, the root directory (/) is actually a bind mount to a path buried in the ostree repository (something like /ostree/boot.1/debian/72448a25b05b4af57ed48c72bea09e50643b90bfaad5125bfd022a6aa67aac2c/0). /var is a better place to write to as it remains a mutable location to store files. In this pull request, I switched tools/grow_partition.sh and boot/generic-startup.sh to write to /var rather than /.
See https://github.com/ostreedev/ostree/issues/2357 for more info about the ostree conversion.
> change path from /resizerootfs to /var/resizerootfs 

- tools/developers/nfs-rsync.sh
- tools/developers/secondary_rootfs.sh
- tools/eMMC/bbb-eMMC-flasher-eewiki-12mb.sh
- tools/eMMC/bbb-eMMC-flasher-eewiki-ext4.sh
- tools/eMMC/functions.sh
- tools/eMMC/init-eMMC-flasher-from-usb-media-v1-bbgw.sh
- tools/eMMC/init-eMMC-flasher-v3-bbbl.sh
- tools/eMMC/init-eMMC-flasher-v3-bbbw.sh
- tools/eMMC/init-eMMC-flasher-v3-bbgw.sh
- tools/non-mmc-rootfs/mv_rootfs_dev_sda.sh
Without this, non-root ping cause 'socket: Operation not permitted' error due to missing xattrs.
Signed-off-by: Atsushi Nemoto <atsushi.nemoto@sord.co.jp>
---
Tested only _copy_files() part of function.sh.
Others are done by just replacing by 's/rsync -aAx/rsync -aAXx/' automatically.
> add rsync -X option

- device/bone/show-pins.pl
This fix worked for me, but I am not a perl expert, I simply tried to apply a script fix from another repository on this version of the script.
See https://github.com/mvduin/bbb-pin-utils/commit/d51ed53ef61935a5e1289d141e9fdd974e2a4f99 for additional information.
> Fix parse error for show-pins.pl

- tools/eMMC/functions.sh
The _exit_trap will be called after _err_trap and LEDs are resetted as OK. Like write_failure, notify the error on LEDs and go inf_loop.
> Do not exit from the _err_trap
